results=dict(file='chain_twExo1_nEndo25_0.uai', folder='set6', error=True, errorMsg='java.util.concurrent.ExecutionException: java.lang.NegativeArraySizeException: -1688109844')
